### ISSUE TITLE
PyEnchant's tokenize module conflicts with stdlib

### ISSUE THREAD

**Issue by Erabior** [pyenchant/pyenchant#251] opened 2021-07-25 17:33 UTC
**Environment**
Python version: 3.9
Operation system: Windows 10 x64

**Additional context**

**Steps to Reproduce**
Please specify steps to reproduce the incorrect behavior: using pip to install pyenchant

**Expected behavior**
Please tell us what you expected to happen: after installing pyenchant, the folder 'tokenize' is created in the Python39\Lib\site-packages\enchant directory. this folder completely breaks python entirely returning any command with AttributeError: module 'tokenize' has no attribute 'open'

**Additional context**

Trying to compile a .py file for example with pyinstaller gives:

```
C:\Users\REDACTED\Documents\My Scripts-Programs\Assasin>pyinstaller -F untitled111.py
Traceback (most recent call last):
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\REDACTED\AppData\Local\Programs\Python\Python39\Scripts\pyinstaller.exe\__main__.py", line 4, in <module>
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\__init__.py", line 54, in <module>
    import pkg_resources
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\__init__.py", line 78, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\extern\__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\extern\__init__.py", line 37, in load_module
    __import__(extant)
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 4756, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1284, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1066, in _trim_arity
    this_line = extract_stack(limit=2)[-1]
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\site-packages\pkg_resources\_vendor\pyparsing.py", line 1050, in extract_stack
    frame_summary = traceback.extract_stack(limit=-offset+limit-1)[offset]
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\traceback.py", line 366, in extract
    f.line
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\traceback.py", line 288, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\linecache.py", line 30, in getline
    lines = getlines(filename, module_globals)
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\linecache.py", line 46, in getlines
    return updatecache(filename, module_globals)
  File "c:\users\REDACTED\appdata\local\programs\python\python39\lib\linecache.py", line 136, in updatecache
    with tokenize.open(fullname) as fp:
AttributeError: module 'tokenize' has no attribute 'open'
```

Thanks!

*Note (dmerejkowsky) edited for better readability*

**Comment by dmerejkowsky** [comment] 2021-07-27 12:52
Hum. I guess it's time to implements one of the previous maintainer's items on their TODO list :)

```markdown 
  * rename "tokenize", it tends to conflict with the top-level stdlib
    module of the same name (although I've no idea why)
```

I have no clue either, but this kind of bug is annoying and should be fixed.

**Comment by dmerejkowsky** [comment] 2021-07-27 13:19
Actually, I'm not sure it's a good idea to rename Enchant's module ... it will break the public API after all.

Also, I did manage to compile a standalone executable with pyinstaller on my machine.

Finally, it looks to me you are not using pyinstaller or enchant from a virtualenv - could you try with one and tell us if the problem persists ?

**Comment by Erabior** [comment] 2021-07-27 14:42
What do you mean by a virtualenv? I installed pyinstaller and enchant using pip the same way I thought everyone does?

**Comment by dmerejkowsky** [comment] 2021-07-27 14:56
>  I installed pyinstaller and enchant using pip the same way I thought everyone does?

Well, lots of people do, and it causes many problems unfortunately :(

There's a good tutorial about virtual environments in the documentation : https://docs.python.org/3/tutorial/venv.html

**Comment by dmerejkowsky** [comment] 2021-09-09 17:27
Sorry I changed the title of the bug a bit too soon. For now we don't really *know* if the lack of virtualenv is the source of the problem.

@Erabior can you confirm that using a virtualenv fixes the problem for you? If not, we'll probably have to close this due to lack of easy way of reproducing the bug ...

**Closed** 2021-11-22 19:19 UTC
