### ISSUE TITLE
ENCHANT_CONFIG_DIR doesn`t specify place for dicts

### ISSUE THREAD

**Issue by Botalik** [pyenchant/pyenchant#234] opened 2021-01-22 07:37 UTC
I tried to specify place for dicts by ENCHANT_CONFIG_DIR, but it doesn`t helped me. I declared variables by os.environ.  Win10. What did i wrong?

**Comment by krbailey** [comment] 2021-06-03 03:01
@Botalik we're you able to figure out how set a custom directory for dictionaries?

**Comment by dmerejkowsky** [comment] 2021-06-28 10:53
Looks like a duplicate of #24. Let's close this in order to keep the relevant discussion in one place.

**Closed by dmerejkowsky** 2021-06-28 10:53 UTC
