### ISSUE TITLE
Bouncing dock icon on macOS

### ISSUE THREAD

**Issue by heilerich** [pyenchant/pyenchant#238] opened 2021-04-28 14:11 UTC
In my current environment invoking pyenchant (e.g. just by importing it) produces a bouncing `Python.app` dock icon. This is especially annoying when a spellchecking tool that uses pyenchant is run regularly. For example my editor makes my dock look like this when editing anything and spell checking is enabled

<details>
<summary>Screen recording</summary>

![2021-04-28 15 55 29](https://user-images.githubusercontent.com/1824236/116416046-4b4f7480-a83a-11eb-931f-9dd5747010dd.gif)

</details>

I think the recording demonstrates how this constant flickering might disturb the editing experience :)

I have narrowed it down to this call https://github.com/pyenchant/pyenchant/blob/b4a8d934a3f5846d7e70b5d54274e9b03777be6c/enchant/__init__.py#L211

which translates to calling `enchant_broker_init` of libenchant. I have verified that any script that just calls that C method will produce a bouncing dock icon.

Usually, bouncing dock icons are caused on macOS when something is trying to interact with the GUI. This seems to be a common problem when people are importing interactive matplotlib backends.

In this case I am unsure if this is caused by `pyenchant` or the underlying library. I have tried importing the C library from a command line tool written in Swift which does not cause a dock icon to appear. This seems to indicate that there is some python specific aspect to the problem.
Otherwise, I have no clue as to why this is happening and how it could be solved.

I would appreciate any ideas, this is really driving me crazy ;|

**Environment**
Python version: 3.9.4
Operation system: macOS Big Sur 11.2.3 (20D91)
Enchant version: 2.2.15 (installed via brew)

**Steps to Reproduce**
```python
import enchant
```

**Comment by dmerejkowsky** [comment] 2021-04-28 14:44
I'm really sorry but I no longer have access to Apple hardware and so I'm unable to help you. Hopefully, someone else will find a solution...

**Comment by dmerejkowsky** [comment] 2021-04-28 15:51
Oh, and just being curious - with what editor are you using PyEnchant?

**Comment by heilerich** [comment] 2021-04-29 08:23
That's unfortunate 😞 

Nothing special about my editor. I am working on some python projects that use pylint, which relies on pyenchant for spell checking strings. The editor is just plain old vim. It executes the linter on every edit, which then causes the flickering dock.

**Comment by dmerejkowsky** [comment] 2021-04-29 11:27
Oh - I did not know that pylint used penchant :) Thanks for letting me know.

**Comment by alexreg** [comment] 2022-05-03 15:18
Note: a very similar issue with a dock icon also occurs on macOS.

**Comment by alexreg** [comment] 2022-05-03 15:52
I've further narrowed down the issue to the AppleSpell provider, which is defined by *enchant* in [this file](https://github.com/AbiWord/enchant/blob/36f1d9af8e0702be61523199ab50a9ca5c65918f/providers/applespell_checker.mm). I think the issue is that it imports Cocoa.

**Comment by dmerejkowsky** [comment] 2022-05-03 16:56
@alexreg thanks for the help. We can close this I guess.

**Closed by dmerejkowsky** 2022-05-03 16:56 UTC
Labels: help-wanted

**Comment by dmerejkowsky** [comment] 2022-05-03 16:57
@alexreg do you want to make a patch to add a few lines in Enchant' s FAQ ?

You may want to open a separate issue for Enchant maintainers and link to it from there, too.

**Comment by alexreg** [comment] 2022-05-03 17:37
@dmerejkowsky Yes, I think so. The problem is either with Enchant or with Python's ctypes. I've opened an issue for ctypes [here](https://github.com/python/cpython/issues/92235#issuecomment-1116348122), since I think that's the most likely culprit.
