### ISSUE TITLE
Infinite loop when using the MySpell provider

### ISSUE THREAD

**Issue by cclink** [pyenchant/pyenchant#136] opened 2019-04-12 03:14 UTC
I use enchant to find the english words in text files. When I check some words, I got a stuck. I wait for a relative long time, but it stuck anyway.

Sample code:
import enchant
d = enchant.Dict("en_US")
d.check("00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FCFD")

But when check for 00000000000000000000FF030202FFFFF8FFEBDBCFC4DAE7FFF908E92820306B or 9544D954000000006C0000000000000000000000000000000000000000000000, it works.

**Comment by dmerejkowsky** [comment] 2019-11-27 09:17
Could not reproduce here. I guess it depends on the provider. Can you try running:

```python
d = enchant.Dict("en_US")
print(vars(d.provider))
```

and posting the output here?

**Comment by jenstroeger** [comment] 2020-01-23 03:29
@dmerejkowsky, yes I can confirm:
```python
>>> d = enchant.Dict('en_US')
>>> d.check("00FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF00FCFD")
_
```
Been sitting there for a while now while the Python process occupies the CPU core at 100%… looks like a stuck loop to me. To answer your above request:
```
>>> d = enchant.Dict('en-US')
>>> d
<enchant.Dict object at 0x104430950>
>>> print(vars(d.provider))
{'name': 'myspell', 'desc': 'Myspell Provider', 'file': '/.../lib/python3.7/site-packages/enchant/lib/enchant/libenchant_myspell.so'}
```

**Comment by cclink** [comment] 2020-01-23 03:38
@dmerejkowsky 
My provider is the same as jenstroeger

>>> import enchant
>>> d = enchant.Dict('en-US')
>>> d
<enchant.Dict object at 0x108015750>
>>> print(vars(d.provider))
{'name': 'myspell', 'desc': 'Myspell Provider', 'file': '/usr/local/lib/python3.7/site-packages/enchant/lib/enchant/libenchant_myspell.so'}

**Comment by dmerejkowsky** [comment] 2020-01-23 09:37
Thank you both. We've confirmed the bug exists and we have a way to reproduce it. I'll take a look on how to fix it.

**Comment by jenstroeger** [comment] 2020-01-23 09:48
@dmerejkowsky, easy fix provided by issue https://github.com/pyenchant/pyenchant/issues/159 😁

**Comment by dmerejkowsky** [comment] 2020-01-23 09:57
Woops, you're right - did not realize the bug only happened with myspel :stuck_out_tongue: 

Let's close this as we probably won't fix it.

**Closed by dmerejkowsky** 2020-01-23 09:57 UTC
