### ISSUE TITLE
No module named 'enchant' after installing enchant with brew and pyenchant with pip

### ISSUE THREAD

**Issue by cbarkachi** [pyenchant/pyenchant#264] opened 2021-11-01 20:41 UTC
**Environment**
Python version: 3.9.2
Operation system: macOS Monterey

**Additional context**
(Mac M1)

**Steps to Reproduce**
`arch -x86_64 brew install enchant`
`pip3 install pyenchant`
`import enchant` in Python shell
```
Traceback (most recent call last):
  File "/Users/chris/school/2022fall/cos432/4-netsec/Crib-Dragging-Auto-Cracker/auto.py", line 1, in <module>
    import enchant
ModuleNotFoundError: No module named 'enchant'
```

**Expected behavior**
for pyenchant to be imported

**Additional context**
N/A

**Comment by dmerejkowsky** [comment] 2021-11-02 08:49
Hum I think the first line installed the enchant C library for x86_64, but if you're on M1, it's possible your are using Python compiled for Arm - so maybe the issue comes from that.

It's also possible you're using a `pip` and a `python` that are on different version. Try this:

```
brew install enchant
python -m pip install --upgrade pip
python -m pip install pyenchant
python -c 'import enchant'
```

**Comment by mtscott321** [comment] 2022-01-01 07:05
I am having the same issue, on PyDroid

![image](https://user-images.githubusercontent.com/37154598/147845651-079a9751-d579-499c-aa8f-86c5ba70952e.png)

**Comment by dmerejkowsky** [comment] 2022-01-01 13:57
Hi @mtscott32 and thanks for the bug report. I'm going to close this issue, which is specify to macOS M1 and is actually a duplicate of #265 - which has been fixe, and re-open it elsewhere.

**Closed by dmerejkowsky** 2022-01-01 13:57 UTC
